<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Google.Protobuf" Version="3.33.0" />
    <PackageReference Include="Grpc.AspNetCore" Version="2.71.0" />
    <PackageReference Include="Grpc.Tools" Version="2.76.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="9.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Tutorium.Shared\Tutorium.Shared.csproj" />
    <ProjectReference Include="..\Tutorium.UserService.Infrastructure\Tutorium.UserService.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Protobuf Include="..\Tutorium.Shared\protos\user.proto" GrpcServices="Server" />
  </ItemGroup>
</Project>
