// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Tutorium.UserService.Infrastructure.Data;

#nullable disable

namespace Tutorium.UserService.Infrastructure.Data.Migrations.v0_1
{
    [DbContext(typeof(PgContext))]
    partial class PgContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Tutorium.UserService.Core.Models.AuthCredential", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AuthCredential");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.EmailPasswordCredential", b =>
                {
                    b.HasBaseType("Tutorium.UserService.Core.Models.AuthCredential");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("EmailPasswordCredential", (string)null);
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.GoogleCredential", b =>
                {
                    b.HasBaseType("Tutorium.UserService.Core.Models.AuthCredential");

                    b.Property<string>("googleKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.ToTable("GoogleCredential", (string)null);
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.YandexCredential", b =>
                {
                    b.HasBaseType("Tutorium.UserService.Core.Models.AuthCredential");

                    b.ToTable("YandexCredential", (string)null);
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.AuthCredential", b =>
                {
                    b.HasOne("Tutorium.UserService.Core.Models.User", "User")
                        .WithMany("Credentials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.EmailPasswordCredential", b =>
                {
                    b.HasOne("Tutorium.UserService.Core.Models.AuthCredential", null)
                        .WithOne()
                        .HasForeignKey("Tutorium.UserService.Core.Models.EmailPasswordCredential", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.GoogleCredential", b =>
                {
                    b.HasOne("Tutorium.UserService.Core.Models.AuthCredential", null)
                        .WithOne()
                        .HasForeignKey("Tutorium.UserService.Core.Models.GoogleCredential", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.YandexCredential", b =>
                {
                    b.HasOne("Tutorium.UserService.Core.Models.AuthCredential", null)
                        .WithOne()
                        .HasForeignKey("Tutorium.UserService.Core.Models.YandexCredential", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Tutorium.UserService.Core.Models.User", b =>
                {
                    b.Navigation("Credentials");
                });
#pragma warning restore 612, 618
        }
    }
}
